version: "3.9"
services:
  translate_api:
    restart: unless-stopped
    container_name: TranslateAPI
#    entrypoint: ["/bin/sh","-c"]
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - 8011:8000